apiVersion: apps/v1.0
kind: Deployment
metadata:
  name: expressapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressapp
  template:
    metadata:
      labels:
        app: expressapp
    spec:
      containers:
        - name: expressapp
          image: tanmaykhannasdocker/devops:v1.0
          ports:
            - containerPort: 8080
